import { Container } from "@/components/ui/Container";
import { buildMetadata } from "@/lib/seo/metadata";

export const metadata = buildMetadata({
  title: "Terms of Use",
  description: "Terms of use for ToolPilot developer tools.",
  path: "/terms",
  keywords: ["toolpilot terms", "developer tools terms"]
});

export default function TermsPage() {
  return (
    <Container>
      <section className="py-16 sm:py-24">
        <h1 className="text-4xl font-semibold tracking-tight text-[#2e295b] sm:text-5xl">Terms of Use</h1>
        <div className="tp-panel mt-8 space-y-6 p-7 text-sm leading-8 text-[#666b86] sm:p-10">
          <p>ToolPilot provides browser-based developer utilities for general technical and educational purposes.</p>
          <p>
            All tools are provided “as is” without warranties of any kind, including guarantees of accuracy,
            reliability, availability, or fitness for a particular purpose.
          </p>
          <p>
            Users are responsible for verifying any output generated by ToolPilot before relying on it in
            production systems, security-sensitive workflows, business-critical logic, or regulated
            environments.
          </p>
          <div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#2e295b]">Acceptable Use</h2>
            <ul className="mt-4 space-y-3">
              <li>• for illegal activities</li>
              <li>• to disrupt the availability of the website</li>
              <li>• to attempt unauthorized access to the platform</li>
              <li>• to run abusive automated scraping that harms service stability</li>
            </ul>
          </div>
          <div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#2e295b]">Service changes</h2>
            <p className="mt-4">
              ToolPilot may update, improve, modify, or remove features over time without prior notice.
            </p>
          </div>
          <div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#2e295b]">Limitation of liability</h2>
            <p className="mt-4">
              To the maximum extent permitted by law, ToolPilot is not liable for losses or damages resulting
              from the use of the site or reliance on generated outputs.
            </p>
          </div>
          <div>
            <h2 className="text-2xl font-semibold tracking-tight text-[#2e295b]">Use at your own discretion</h2>
            <p className="mt-4">
              ToolPilot is intended to be helpful during technical workflows, but developers should always
              validate outputs independently before production use.
            </p>
          </div>
        </div>
      </section>
    </Container>
  );
}
